//! Reproducible random instance generation, for benchmarks and tests.
//!
//! The PRNG here is a hand-rolled SplitMix64 rather than the `rand` crate. That is
//! deliberate: benchmark numbers and test fixtures are only comparable across time
//! if `(kind, rows, cols, seed)` maps to the same instance forever, and `rand` makes
//! no such guarantee across versions. Ten lines of SplitMix64 pins it permanently
//! and drops a dependency.

use std::fmt::Write as _;

/// SplitMix64: the reference finalizer, used as a standalone generator.
struct SplitMix64(u64);

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform in `[lo, hi]`, inclusive. Uses the multiply-shift reduction, whose
    /// bias is negligible for the small ranges used here.
    fn range(&mut self, lo: i64, hi: i64) -> i64 {
        debug_assert!(lo <= hi);
        let span = (hi - lo + 1) as u64;
        lo + ((self.next_u64() as u128 * span as u128) >> 64) as i64
    }
}

/// The structure of a generated instance.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    /// `min c'x` subject to `a_i'x >= ceil(f * sum(a_i))` with positive `a`.
    ///
    /// The binding right-hand side makes these genuinely hard: the LP relaxation is
    /// tight but fractional, and pure enumeration blows up quickly.
    Knapsack,
    /// `min c'x` subject to `sum_{j in S_i} x_j >= 1`.
    ///
    /// Classic set covering. Easy for LP-based search, hard to prove optimal by
    /// enumeration alone.
    Covering,
    /// `min c'x` subject to `a_i'x >= b_i` with *signed* `a` and a binding `b`.
    ///
    /// Like the `v*c*` sample family, but with each row's right-hand side anchored
    /// at `a_i'x*` for one random witness point `x*` shared by every row.
    ///
    /// Both halves of that matter. Anchoring at a shared witness makes the instance
    /// feasible by construction, independently drawn right-hand sides large enough
    /// to exclude the origin almost always over-constrain each other into
    /// infeasibility. And each row is sign-flipped as needed to keep its right-hand
    /// side positive, which excludes the origin: with a slack `b` the origin is
    /// feasible, and since every objective coefficient is positive the answer would
    /// be trivially `x = 0`.
    Signed,
}

/// What to generate. `(kind, n_cols, n_rows, seed)` fully determines the instance.
#[derive(Clone, Copy, Debug)]
pub struct Spec {
    pub kind: Kind,
    pub n_cols: usize,
    pub n_rows: usize,
    pub seed: u64,
}

impl Spec {
    /// A stable, filesystem-safe name, e.g. `knapsack_c60_r30_s42`.
    pub fn name(&self) -> String {
        let kind = match self.kind {
            Kind::Knapsack => "knapsack",
            Kind::Covering => "covering",
            Kind::Signed => "signed",
        };
        format!("{kind}_c{}_r{}_s{}", self.n_cols, self.n_rows, self.seed)
    }

    /// Render the instance as LP-format text.
    pub fn to_lp(&self) -> String {
        // Mixing the seed with the shape means neighbouring sizes are independent
        // draws rather than prefixes of one another.
        let mut rng = SplitMix64::new(
            self.seed.wrapping_mul(0x2545_F491_4F6C_DD1D)
                ^ ((self.n_cols as u64) << 32)
                ^ self.n_rows as u64,
        );
        let n = self.n_cols;
        let obj: Vec<i64> = (0..n).map(|_| rng.range(1, 100)).collect();

        // A witness point, drawn only for `Signed`, so the other kinds' instances are
        // unaffected by its position in the random stream.
        let witness: Vec<i64> = if self.kind == Kind::Signed {
            // Every `Signed` row redraws its coefficients until `a'x*` is nonzero, and
            // an all-zero witness makes that sum zero for *every* draw, so the redraw
            // never ends. One witness in `2^n_cols` is all zeros -- `signed_c10_r8_s56`
            // is the first such seed at ten columns -- and generating it hung outright
            // rather than failing. Drawing again is the whole fix: it only changes the
            // seeds that produced no model at all.
            loop {
                let draw: Vec<i64> = (0..n).map(|_| rng.range(0, 1)).collect();
                if draw.iter().any(|&w| w != 0) {
                    break draw;
                }
            }
        } else {
            Vec::new()
        };

        let mut s = String::new();
        let _ = writeln!(s, "\\ {}", self.name());
        let _ = writeln!(
            s,
            "\\ generated by ripsolve; {} binary variables, {} constraints",
            n, self.n_rows
        );
        s.push_str("Minimize\n obj:");
        for (j, c) in obj.iter().enumerate() {
            let _ = write!(s, " + {c} x{j}");
        }
        s.push_str("\nSubject To\n");

        for i in 0..self.n_rows {
            match self.kind {
                Kind::Knapsack => {
                    let a: Vec<i64> = (0..n).map(|_| rng.range(1, 50)).collect();
                    let rhs = a.iter().sum::<i64>() / 2;
                    let _ = write!(s, " c{i}:");
                    for (j, v) in a.iter().enumerate() {
                        let _ = write!(s, " + {v} x{j}");
                    }
                    let _ = writeln!(s, " >= {rhs}");
                }
                Kind::Covering => {
                    // Each row covers a random subset; at least two columns so no row
                    // is a singleton that presolve would immediately fix.
                    let mut members: Vec<usize> =
                        (0..n).filter(|_| rng.range(0, 99) < 25).collect();
                    while members.len() < 2 {
                        let j = rng.range(0, n as i64 - 1) as usize;
                        if !members.contains(&j) {
                            members.push(j);
                        }
                    }
                    members.sort_unstable();
                    let _ = write!(s, " c{i}:");
                    for j in members {
                        let _ = write!(s, " + x{j}");
                    }
                    let _ = writeln!(s, " >= 1");
                }
                Kind::Signed => {
                    // Redraw on the measure-zero case `a'x* == 0`, where no sign
                    // choice can put the right-hand side on the positive side of zero.
                    let (mut a, mut rhs) = loop {
                        let a: Vec<i64> = (0..n).map(|_| rng.range(-128, 127)).collect();
                        let t: i64 = a.iter().zip(&witness).map(|(v, w)| v * w).sum();
                        if t != 0 {
                            break (a, t);
                        }
                    };
                    if rhs < 0 {
                        for v in &mut a {
                            *v = -*v;
                        }
                        rhs = -rhs;
                    }
                    let _ = write!(s, " c{i}:");
                    for (j, v) in a.iter().enumerate() {
                        let sign = if *v < 0 { '-' } else { '+' };
                        let _ = write!(s, " {sign} {} x{j}", v.abs());
                    }
                    let _ = writeln!(s, " >= {rhs}");
                }
            }
        }

        s.push_str("Binary\n");
        for j in 0..n {
            let _ = write!(s, " x{j}");
        }
        s.push_str("\nEnd\n");
        s
    }
}

/// FNV-1a (64-bit) over the instance's LP text.
///
/// Test fixtures record reference values computed by an external oracle for a
/// specific instance; this digest is what lets a test notice that the generator has
/// since changed and the recorded values no longer describe the instance being
/// solved. FNV-1a is chosen only because it is trivial to reimplement identically
/// in the fixture-refresh script: it is a change detector, not a security hash.
pub fn lp_digest(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in text.as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Problem;
    use lp_parser_rs::problem::LpProblem;

    fn build(spec: Spec) -> Problem {
        let text = spec.to_lp();
        let lp = LpProblem::parse(&text).unwrap_or_else(|e| panic!("{}: {e}\n{text}", spec.name()));
        let p = Problem::from_lp(&lp).unwrap();
        p.validate().unwrap();
        p
    }

    #[test]
    fn every_kind_round_trips_through_the_reader() {
        for kind in [Kind::Knapsack, Kind::Covering, Kind::Signed] {
            let spec = Spec {
                kind,
                n_cols: 25,
                n_rows: 12,
                seed: 7,
            };
            let p = build(spec);
            assert_eq!(p.n_cols(), 25, "{kind:?}");
            assert_eq!(p.n_rows(), 12, "{kind:?}");
            assert!(p.matrix.nnz() > 0, "{kind:?}");
        }
    }

    #[test]
    fn generation_is_reproducible() {
        let spec = Spec {
            kind: Kind::Knapsack,
            n_cols: 30,
            n_rows: 15,
            seed: 42,
        };
        assert_eq!(spec.to_lp(), spec.to_lp());
    }

    #[test]
    fn digest_tracks_the_text() {
        let spec = Spec {
            kind: Kind::Knapsack,
            n_cols: 30,
            n_rows: 15,
            seed: 42,
        };
        assert_eq!(lp_digest(&spec.to_lp()), lp_digest(&spec.to_lp()));
        assert_ne!(
            lp_digest(&spec.to_lp()),
            lp_digest(&Spec { seed: 43, ..spec }.to_lp())
        );
        // Pinned so a change to FNV-1a itself is caught, not just a change upstream.
        // The subject is deliberately unrelated to the crate name, so renaming the
        // project cannot invalidate the constant.
        assert_eq!(lp_digest("fnv-1a reference"), 0x5a1b_1e03_e488_6553);
    }

    #[test]
    fn seed_and_shape_both_change_the_instance() {
        let base = Spec {
            kind: Kind::Knapsack,
            n_cols: 30,
            n_rows: 15,
            seed: 42,
        };
        let other_seed = Spec { seed: 43, ..base };
        let other_shape = Spec { n_rows: 16, ..base };
        assert_ne!(base.to_lp(), other_seed.to_lp());
        assert_ne!(base.to_lp(), other_shape.to_lp());
    }

    #[test]
    fn covering_rows_are_never_singletons() {
        // A singleton covering row forces its variable to 1, which would make the
        // instance a presolve exercise rather than a search one.
        let spec = Spec {
            kind: Kind::Covering,
            n_cols: 12,
            n_rows: 40,
            seed: 3,
        };
        let p = build(spec);
        let csr = p.matrix.to_csr();
        for i in 0..p.n_rows() {
            assert!(csr.column(i).0.len() >= 2, "row {i} is a singleton");
        }
    }

    #[test]
    fn signed_instances_are_feasible_by_construction() {
        // The witness point satisfies every row, so a solver must never report this
        // family infeasible. Recomputing it here from the emitted model is the check
        // that the anchoring actually survived into the file.
        let spec = Spec {
            kind: Kind::Signed,
            n_cols: 32,
            n_rows: 24,
            seed: 11,
        };
        let p = build(spec);
        let csr = p.matrix.to_csr();
        // Find any feasible point by brute force over the witness we know exists:
        // every row's lb equals a'x* exactly, so the row activities must be
        // simultaneously achievable. Verify via the LP bound instead: each row's
        // lower bound must be reachable by some 0/1 assignment of that row.
        for i in 0..p.n_rows() {
            let (_, vals) = csr.column(i);
            let max_activity: f64 = vals.iter().filter(|v| **v > 0.0).sum();
            assert!(
                p.row_lb[i] <= max_activity,
                "row {i} needs {} but its maximum activity is {max_activity}",
                p.row_lb[i]
            );
        }
    }

    #[test]
    fn the_origin_is_infeasible_where_it_should_be() {
        // If x = 0 satisfies every row, the instance is vacuous: all objective
        // coefficients are positive, so the optimum is 0 and nothing is searched.
        for kind in [Kind::Knapsack, Kind::Covering, Kind::Signed] {
            let p = build(Spec {
                kind,
                n_cols: 32,
                n_rows: 20,
                seed: 5,
            });
            let violated = (0..p.n_rows()).any(|i| p.row_lb[i] > 0.0);
            assert!(
                violated,
                "{kind:?}: x = 0 is feasible, so the instance is trivial"
            );
        }
    }

    #[test]
    fn splitmix_range_stays_in_bounds() {
        let mut rng = SplitMix64::new(1);
        for _ in 0..10_000 {
            let v = rng.range(-5, 5);
            assert!((-5..=5).contains(&v));
        }
        // A degenerate range must return its single value, not panic or wrap.
        assert_eq!(rng.range(3, 3), 3);
    }
}
#[cfg(test)]
mod witness_tests {
    use super::*;

    /// Every seed produces a model, rather than some seed producing none forever.
    ///
    /// `Signed` rows redraw their coefficients until `a'x*` is nonzero against a shared
    /// witness `x*`, so an all-zero witness spins that redraw for ever. It is one seed
    /// in `2^n_cols`, which at ten columns is rare enough to sit unnoticed and common
    /// enough for a sweep over a couple of hundred seeds to hit: `signed_c10_r8_s56` is
    /// the first. This fails by not finishing, which is what the bug did.
    #[test]
    fn every_signed_seed_generates_a_model() {
        for n_cols in [8usize, 10, 12] {
            for seed in 0..256u64 {
                let spec = Spec {
                    kind: Kind::Signed,
                    n_cols,
                    n_rows: 8,
                    seed,
                };
                assert!(
                    !spec.to_lp().is_empty(),
                    "{} generated nothing",
                    spec.name()
                );
            }
        }
    }
}
