[package]
name = "bipper"
description = "A branch-and-cut solver for binary integer programs, in pure Rust."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
lp_parser_rs.workspace = true
serde_json = "1"

[dependencies]
thiserror.workspace = true
lp_parser_rs.workspace = true
